/**:
  ros__parameters:
    # Essentials
    control_freq_hz: 50.0
    kp_xy: 0.15
    ki_xy: 0.006
    
    # Limits (for ros2_bebop_driver)
    max_tilt_angle_deg: 17.5
    max_vertical_speed_mps: 1.0
    max_rotation_speed_dps: 150.0

    # Topics (I'm hoping my edits namespace these right)
    odom_topic: "filtered_odom/rho"
    des_vel_topic: "cmd_vel_des"
    cmd_vel_topic: "cmd_vel"
    bebop_mode_topic: "mode"
